### PR TITLE
Ansible

### PR DESCRIPTION
**Pull request by ltoning**
Release notes **ElimuPI release 3.0.0**

- Image is based on the most recent Raspbian OS 64 bit version. ([ issue 36 ](https://github.com/DEAN-ngo/elimupi/issues/36)en[ issue 91](https://github.com/DEAN-ngo/elimupi/issues/91) )
- Image was created via an Ansible installation. ( [issue 22](https://github.com/DEAN-ngo/elimupi/issues/22) en [issue 92](https://github.com/DEAN-ngo/elimupi/issues/92)).
- Kolibri version 0.15.7 and uses files on the content disk ( [issue 24](https://github.com/DEAN-ngo/elimupi/issues/24)).
- Added Nginx vhost admin.elimupi.online ( [issue 34](https://github.com/DEAN-ngo/elimupi/issues/34) ).
- Nginx vhost kolibri.elimupi.online is available on port 80 instead of 8080.
- Moodle version 4.0.3 is installed but not yet fully configured or ready for use.

### CODE REVIEW

**Comment by jer0enA** [comment]
When following the instructions in the ` README.md`  I got the error in ansible after a while about restarting Nginx.

```
RUNNING HANDLER [common : Restart Nginx] ****************************************************************************************************************************************************************
fatal: [raspberrypi]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
```

```
root@elimupi:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-10-04 15:17:11 CEST; 2min 10s ago
       Docs: man:nginx(8)
    Process: 51823 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 37ms

Oct 04 15:17:11 elimupi systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 04 15:17:11 elimupi nginx[51823]: nginx: [emerg] open() "/mnt/content/kolibri-home/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
Oct 04 15:17:11 elimupi nginx[51823]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Failed with result 'exit-code'.
Oct 04 15:17:11 elimupi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```

I didn't add the content disk yet is that maybe the problem? If so should we add this to the instructions?

**Comment by ltoning** [comment]
> When following the instructions in the ` README.md` I got the error in ansible after a while about restarting Nginx.
> 
> ```
> RUNNING HANDLER [common : Restart Nginx] ****************************************************************************************************************************************************************
> fatal: [raspberrypi]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
> ```
> 
> ```
> root@elimupi:~# systemctl status nginx.service
> ● nginx.service - A high performance web server and a reverse proxy server
>      Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Tue 2022-10-04 15:17:11 CEST; 2min 10s ago
>        Docs: man:nginx(8)
>     Process: 51823 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
>         CPU: 37ms
> 
> Oct 04 15:17:11 elimupi systemd[1]: Starting A high performance web server and a reverse proxy server...
> Oct 04 15:17:11 elimupi nginx[51823]: nginx: [emerg] open() "/mnt/content/kolibri-home/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
> Oct 04 15:17:11 elimupi nginx[51823]: nginx: configuration file /etc/nginx/nginx.conf test failed
> Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
> Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Failed with result 'exit-code'.
> Oct 04 15:17:11 elimupi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
> ```
> 
> I didn't add the content disk yet is that maybe the problem? If so should we add this to the instructions?

Yes, adding the content disk should resolve the isssue for now
Maybe we can make the install independent of the content disk. Will investigate.

**Comment by ltoning** [comment]
> > When following the instructions in the ` README.md` I got the error in ansible after a while about restarting Nginx.
> > ```
> > RUNNING HANDLER [common : Restart Nginx] ****************************************************************************************************************************************************************
> > fatal: [raspberrypi]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@elimupi:~# systemctl status nginx.service
> > ● nginx.service - A high performance web server and a reverse proxy server
> >      Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
> >      Active: failed (Result: exit-code) since Tue 2022-10-04 15:17:11 CEST; 2min 10s ago
> >        Docs: man:nginx(8)
> >     Process: 51823 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
> >         CPU: 37ms
> > 
> > Oct 04 15:17:11 elimupi systemd[1]: Starting A high performance web server and a reverse proxy server...
> > Oct 04 15:17:11 elimupi nginx[51823]: nginx: [emerg] open() "/mnt/content/kolibri-home/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
> > Oct 04 15:17:11 elimupi nginx[51823]: nginx: configuration file /etc/nginx/nginx.conf test failed
> > Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
> > Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Failed with result 'exit-code'.
> > Oct 04 15:17:11 elimupi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I didn't add the content disk yet is that maybe the problem? If so should we add this to the instructions?
> 
> Yes, adding the content disk should resolve the isssue for now Maybe we can make the install independent of the content disk. Will investigate.

> > When following the instructions in the ` README.md` I got the error in ansible after a while about restarting Nginx.
> > ```
> > RUNNING HANDLER [common : Restart Nginx] ****************************************************************************************************************************************************************
> > fatal: [raspberrypi]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > root@elimupi:~# systemctl status nginx.service
> > ● nginx.service - A high performance web server and a reverse proxy server
> >      Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
> >      Active: failed (Result: exit-code) since Tue 2022-10-04 15:17:11 CEST; 2min 10s ago
> >        Docs: man:nginx(8)
> >     Process: 51823 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
> >         CPU: 37ms
> > 
> > Oct 04 15:17:11 elimupi systemd[1]: Starting A high performance web server and a reverse proxy server...
> > Oct 04 15:17:11 elimupi nginx[51823]: nginx: [emerg] open() "/mnt/content/kolibri-home/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
> > Oct 04 15:17:11 elimupi nginx[51823]: nginx: configuration file /etc/nginx/nginx.conf test failed
> > Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
> > Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Failed with result 'exit-code'.
> > Oct 04 15:17:11 elimupi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I didn't add the content disk yet is that maybe the problem? If so should we add this to the instructions?
> 
> Yes, adding the content disk should resolve the isssue for now Maybe we can make the install independent of the content disk. Will investigate.



> When following the instructions in the ` README.md` I got the error in ansible after a while about restarting Nginx.
> 
> ```
> RUNNING HANDLER [common : Restart Nginx] ****************************************************************************************************************************************************************
> fatal: [raspberrypi]: FAILED! => {"changed": false, "msg": "Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.\nSee \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
> ```
> 
> ```
> root@elimupi:~# systemctl status nginx.service
> ● nginx.service - A high performance web server and a reverse proxy server
>      Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Tue 2022-10-04 15:17:11 CEST; 2min 10s ago
>        Docs: man:nginx(8)
>     Process: 51823 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
>         CPU: 37ms
> 
> Oct 04 15:17:11 elimupi systemd[1]: Starting A high performance web server and a reverse proxy server...
> Oct 04 15:17:11 elimupi nginx[51823]: nginx: [emerg] open() "/mnt/content/kolibri-home/nginx.conf" failed (2: No such file or directory) in /etc/kolibri/nginx.d/099-user.conf:1
> Oct 04 15:17:11 elimupi nginx[51823]: nginx: configuration file /etc/nginx/nginx.conf test failed
> Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
> Oct 04 15:17:11 elimupi systemd[1]: nginx.service: Failed with result 'exit-code'.
> Oct 04 15:17:11 elimupi systemd[1]: Failed to start A high performance web server and a reverse proxy server.
> ```
> 
> I didn't add the content disk yet is that maybe the problem? If so should we add this to the instructions?

I will add a fix to make the Ansible install independent of weather the contentdisk is inserted.

**Review by marcobruining — APPROVED** [review]

**Comment by ltoning** [comment]
Release 3.0.0

**Pull request merged**
