### PR TITLE
Openldap

### PR DESCRIPTION
**Pull request by pieterhoekstra**
This branch adds:
- LDAP
- PHP ini: set max-upload-filesize to 2GB for upload APK's
- Enable locales Kenia etc for translations
- Install Moosh 1.4

### CODE REVIEW

**Comment by ltoning** [comment]
@pieterhoekstra can you please confirm if we can close this PR?
All neded changes should be in now be in release [v3.1.0]( https://github.com/DEAN-ngo/elimupi/releases/tag/v3.1.0)

**Comment by pieterhoekstra** [comment]
@ltoning Passwords don't work yet: they were hashed (before ansible) like 
`userPassword: {SSHA}qv4BGoBhku6AfD+Nla19ov0Tg0iRKUHT`
and now they are like
`userPassword:: e1NTSEF9cXY0QkdvQmhrdTZBZkQrTmxhMTlvdjBUZzBpUktVSFQ=`
By using plaintext when creating/updating an account the problem persists

**Comment by ltoning** [comment]
> @ltoning Passwords don't work yet: they were hashed (before ansible) like `userPassword: {SSHA}qv4BGoBhku6AfD+Nla19ov0Tg0iRKUHT` and now they are like `userPassword:: e1NTSEF9cXY0QkdvQmhrdTZBZkQrTmxhMTlvdjBUZzBpUktVSFQ=` By using plaintext when creating/updating an account the problem persists

@pieterhoekstra  LDAP authentication is working fine using the set password.
The passwords are being presented in base64 encoded. ( note the :: in userPassword:: )

$ echo e1NTSEF9cXY0QkdvQmhrdTZBZkQrTmxhMTlvdjBUZzBpUktVSFQ=|openssl base64 -d
{SSHA}qv4BGoBhku6AfD+Nla19ov0Tg0iRKUHT

**Comment by pieterhoekstra** [comment]
@ltoning Bug had to do with implementation of ldap_list(). Pushed an update to the WebInterface repo. Issue can be closed.

**Pull request closed without merging**
